version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-rybbit}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:-rybbit}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-default}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server/config.d
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - CLICKHOUSE_HOST=clickhouse
      - DOMAIN_NAME=${DOMAIN_NAME:-localhost:8080}
      - BASE_URL=${BASE_URL:-http://localhost:8080}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_started

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    ports:
      - "3002:3002"
    depends_on:
      - backend

volumes:
  postgres_data:
  clickhouse_data: